version: '3'

services:
  postgres:
    image: 'postgres:13'
    container_name: 'aikam-postgres'
    ports:
      - 1000:5432
    environment:
      - 'POSTGRES_USER=sa'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=aikam'
